- hosts: all
  tasks:
   - name: Install all
     apt: name={{ item }} update_cache=yes state=present
     with_items:
        - nginx
        - apache2
        - php7.0
        - libapache2-mod-php7.0
        - php7.0-mbstring
        - libapache2-mpm-itk
        - unzip
     sudo: yes
   - name: Create directories
     file: path={{item}} state=directory  mode=0755
     with_items:
        - /var/www/test1.local
        - /var/www/test2.local
        - /etc/nginx/sites-available
     sudo: yes
   - name: Enable mpm-itk
     apache2_module: name={{item}} state=present
     with_items:
        - mpm_prefork
        - mpm_itk
   - name: Add groups
     group: name={{item}} state=present
     with_items:
        - testwww1
        - testwww2
     sudo: yes
   - name: add several users
     user: name={{ item.name }} groups={{ item.groups}} state=present
     with_items:
        - { name: testwww1, groups: testwww1 }
        - { name: testwww2, groups: testwww2 }
     sudo: yes
   - name: add www-data to our groups
     user: name=www-data groups=testwww1,testwww2 append=yes
     sudo: yes
   - name: Copy all we need
     copy: src={{ item.src }} dest={{ item.dest }}
     with_items:
        - { src: 'test1.conf', dest: '/etc/nginx/sites-available/test1.conf' }
#        - { src: 'index1.php', dest: '/var/www/test1.local/index.php' }
        - { src: 'test2.conf', dest: '/etc/nginx/sites-available/test2.conf' }
#        - { src: 'index2.php', dest: '/var/www/test2.local/index.php' }
        - { src: 'nginx.conf', dest: '/etc/nginx/nginx.conf' }
        - { src: 'ports.conf', dest: '/etc/apache2/ports.conf' }
        - { src: '000-default.conf', dest: '/etc/apache2/sites-available/000-default.conf' }
        - { src: '001-default.conf', dest: '/etc/apache2/sites-available/001-default.conf' }
        - { src: 'microText-v0.6.zip', dest: '/tmp/microText-v0.6.zip' }
     sudo: yes
   - name: Unarchive a site
     unarchive: src=/tmp/microText-v0.6.zip dest={{item}} copy=no
     with_items:
        - /var/www/test1.local
        - /var/www/test2.local
     sudo: yes
   - name: Copy all we need 2
     copy: src={{ item.src }} dest={{ item.dest }}
     with_items:
        - { src: '1config.inc.php', dest: '/var/www/test1.local/config.inc.php' }
        - { src: '.htaccess', dest: '/var/www/test1.local/.htaccess' }
        - { src: '2config.inc.php', dest: '/var/www/test2.local/config.inc.php' }
        - { src: '.htaccess', dest: '/var/www/test2.local/.htaccess' }
     sudo: yes
   - name: ownership of test1
     file: path=/var/www/test1.local owner=testwww1 group=testwww1 mode=0750 state=directory recurse=yes
     sudo: yes
   - name: ownership of test2
     file: path=/var/www/test2.local owner=testwww2 group=testwww2 mode=0750 state=directory recurse=yes
     sudo: yes
   - name: vhost test2.local apache link
     file: src=/etc/apache2/sites-available/001-default.conf dest=/etc/apache2/sites-enabled/001-default.conf state=link
     sudo: yes
   - name: php.ini - Change memory limit to 256M
     replace: dest=/etc/php/7.0/apache2/php.ini regexp='^memory_limit = .*$' replace='memory_limit = 256M'
     sudo: yes
   - name: restart apache2
     service: name=apache2 state=restarted
     sudo: yes
   - name: restart nginx
     service: name=nginx state=restarted
     sudo: yes